"""empty message

Revision ID: 138bf3e780ae
Revises: 
Create Date: 2021-05-22 21:49:48.353345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138bf3e780ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_skill_bar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_skill_bar',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('skill_name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('skill_persantage', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
