"""update

Revision ID: 8df91dd97590
Revises: 
Create Date: 2021-05-18 18:38:38.062191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df91dd97590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('project_name', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('project_img', sa.String(length=50), nullable=True))
    op.drop_column('post', 'portfolio_img_url')
    op.drop_column('post', 'portfolio_category_name')
    op.drop_column('post', 'portfolio_name')
    op.drop_column('post', 'portfolio_header_title')
    op.drop_column('post', 'portfolio_add_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('portfolio_add_date', sa.VARCHAR(length=50), nullable=True))
    op.add_column('post', sa.Column('portfolio_header_title', sa.VARCHAR(length=50), nullable=True))
    op.add_column('post', sa.Column('portfolio_name', sa.VARCHAR(length=50), nullable=True))
    op.add_column('post', sa.Column('portfolio_category_name', sa.VARCHAR(length=50), nullable=True))
    op.add_column('post', sa.Column('portfolio_img_url', sa.VARCHAR(length=50), nullable=True))
    op.drop_column('post', 'project_img')
    op.drop_column('post', 'project_name')
    # ### end Alembic commands ###
